version: "3.5"

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
      - POSTGRES_MAX_CONNECTIONS=200
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "135MB"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
    - db
    logging:
      driver: none

  api01: &api
    image: java-puro:latest
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - server.port=8081
    ports:
      - "8081:8081"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - server.port=8082
    ports:
      - "8082:8082"


  warmup:
    image: curlimages/curl:latest
    depends_on:
      - api01
      - api02
    command: ["sh", "-c", "sleep 10 && curl http://api01:8081/clientes/1/transacoes && curl http://api02:8082/clientes/1/transacoes"]

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "15MB"