FROM openjdk:21
COPY target/java-puro-1.0-SNAPSHOT-jar-with-dependencies.jar /usr/src/app/java-puro-1.0-SNAPSHOT-jar-with-dependencies.jar
WORKDIR /usr/src/app
CMD ["java", "-jar", "java-puro-1.0-SNAPSHOT-jar-with-dependencies.jar"]
