version: "3.5"

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
#    deploy:
#      resources:
#        limits:
#          cpus: "0.13"
#          memory: "140MB"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

  api01: &api
    build: ./api-spring
    image: api-spring:latest
    hostname: api01
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8081:8080"
    depends_on:
      - db
#    deploy:
#      resources:
#        limits:
#          cpus: "0.6"
#          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"