version: "3.5"

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    command: [ "docker-entrypoint.sh", "postgres", "-c", "log_statement=all" ]
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "65MB"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

  api01: &api
    build: ./api-spring
    image: api-spring:latest
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - server.port=8081
    depends_on:
      - db
    env_file:
      - dev.jvm.conf
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "237MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - server.port=8082
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "11MB"

#networks:
#  my_network:
#    driver: host